### ISSUE TITLE
[Bug] Authorization issues

### ISSUE THREAD

**Issue by javiercanillas** [temporalio/web#493]
**Describe the bug**
Enabling Auth0 configuration on temporal-web following the [documentation](https://docs.temporal.io/devtools/web-ui#configuring-authentication) works only as authentication mechanism, but doesn't validate authorization (scopes / roles) of the authenticated user.

**To Reproduce**
1. Create an application client on Auth0 using `https://temporal-web.mytest.com/auth/sso_callback` as callback. Write down client_id and client_secret for future use
2. Create an audience called **test_audience** and add it a scope called **access**
3. Configure temporal-web to use auth the following way (using client_id and client_secret from steps below):
```yaml
auth:
  enabled: true
  providers:
    - label: "Auth0 oidc"
      type: oidc
      issuer: https://XXXXXX.auth0.com/
      client_id:  [CLIENT_ID]
      client_secret: [CLIENT_SECRET]
      scope: openid profile email access
      audience: test_audience
      callback_base_uri: https://temporal-web.mytest.com/ 
      pass_id_token: false
```
**Note:** I added **access** as a required scope to assure that the current authenticated user do has that scope
5. Navigate to https://temporal-web-.mytest.com/  and check that the login page pops up.
6. Login with a valid user without the required **access** scope on the **test_audience** audience
7. User is authorized to login and navigate.

**Expected behavior**
What I was expecting is that a user without the required scopes cannot login and navigate temporal-web in any way.

**Screenshots**
None

**Desktop (please complete the following information where relevant):**
 - OS: MacOS 12.3.1
 - Browser: Chrome
 - Temporal Web Version: 1.15.0
 - using Docker images with some customization
